version: '3'
services:
  web:
    build: ${WEBAPP_STORAGE_HOME}
    restart: always
    ports:
     - "80:80"
    depends_on:
       - db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=demodb
    volumes:
      - ${WEBAPP_STORAGE_HOME}/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always